version: 2

sources:
  - name: hr
    database: raw
    schema: hr
    tables:
      - name: employees
        description: Employee demographic data
      - name: departments
        description: Department & organizational structure data
      - name: compensation
        description: Salary & compensation records
